INSERT INTO skills (name, category) VALUES
  ('Web Development', 'tech'),
  ('App Development', 'tech'),
  ('React', 'tech'),
  ('Angular', 'tech'),
  ('Vue.js', 'tech'),
  ('Java', 'tech'),
  ('Python', 'tech'),
  ('JavaScript', 'tech'),
  ('Node.js', 'tech'),
  ('Data Science', 'tech'),
  ('Machine Learning', 'tech'),
  ('UI/UX Design', 'tech'),
  ('Graphic Design', 'tech'),
  ('Video Editing', 'tech'),
  ('Digital Marketing', 'tech'),
  ('Computer Repair', 'tech'),
  ('Software Development', 'tech'),
  ('DevOps', 'tech'),
  ('Cloud Computing', 'tech'),
  ('Cybersecurity', 'tech'),
  ('Electrician', 'non-tech'),
  ('Plumber', 'non-tech'),
  ('Carpenter', 'non-tech'),
  ('Painter', 'non-tech'),
  ('Driver', 'non-tech'),
  ('Tutor', 'non-tech'),
  ('Delivery', 'non-tech'),
  ('Cleaning', 'non-tech'),
  ('Photography', 'non-tech'),
  ('Event Management', 'non-tech'),
  ('Home Services', 'non-tech'),
  ('Cooking', 'non-tech'),
  ('Gardening', 'non-tech'),
  ('Tailoring', 'non-tech'),
  ('AC Repair', 'non-tech')
ON CONFLICT (name) DO NOTHING;
